package function;

import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class HomePage extends javax.swing.JFrame {

    public HomePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblbookid = new javax.swing.JLabel();
        lblbookauthor = new javax.swing.JLabel();
        lblbooktype = new javax.swing.JLabel();
        lblbooktitle = new javax.swing.JLabel();
        txtbooktitle = new javax.swing.JTextField();
        txtbookauthor = new javax.swing.JTextField();
        txtbookid = new javax.swing.JTextField();
        cmbbooktype = new javax.swing.JComboBox<>();
        btnsave = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        lblBookCat = new javax.swing.JLabel();
        txtBookCat = new javax.swing.JTextField();
        btnFileEdit = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblbookid.setText("Book  Id");

        lblbookauthor.setText("Book  Author");

        lblbooktype.setText("Book Type");

        lblbooktitle.setText("Book  Title");

        cmbbooktype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Computer Science", "Mathematics", "Languages", "Management" }));
        cmbbooktype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbbooktypeActionPerformed(evt);
            }
        });

        btnsave.setText("Save");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel5.setText("Home  Page");

        lblBookCat.setText("Book Category");

        btnFileEdit.setText("File edit");

        btnLogout.setText("Logout");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblbooktitle)
                                .addComponent(lblbooktype))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblbookauthor)
                                    .addComponent(lblbookid))))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtbooktitle, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                            .addComponent(txtbookauthor)
                            .addComponent(txtbookid)
                            .addComponent(cmbbooktype, 0, 156, Short.MAX_VALUE)
                            .addComponent(txtBookCat))
                        .addGap(84, 84, 84))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnsave)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblBookCat))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnFileEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLogout)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cmbbooktype, txtbookauthor, txtbookid, txtbooktitle});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFileEdit)
                    .addComponent(btnLogout))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblbooktype)
                    .addComponent(cmbbooktype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblbooktitle)
                    .addComponent(txtbooktitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblbookauthor)
                    .addComponent(txtbookauthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblbookid)
                    .addComponent(txtbookid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBookCat)
                    .addComponent(txtBookCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(btnsave)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbbooktypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbbooktypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbbooktypeActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        String book_Type = (String) cmbbooktype.getSelectedItem();
        String book_title = txtbooktitle.getText();
        String book_Author = txtbookauthor.getText();
        String book_Id = txtbookid.getText();
        String book_Category = txtBookCat.getText();

        String sql = "INSERT INTO Book VALUES ('" + book_Id + "','" + book_title + "','" + book_Type + "','" + book_Author + "','" + book_Category + "')";
        Connection connection = new DBconnection().connect();
        try {
            PreparedStatement ps = connection.prepareStatement(sql);
            int added = ps.executeUpdate();
            if (added > 0) {
                JOptionPane.showMessageDialog(this, "Added Successful");
                cmbbooktype.getSelectedItem();
                txtbooktitle.setText("");
                txtbookauthor.setText("");
                txtbookid.setText("");
                txtBookCat.setText("");
            } else {
                JOptionPane.showMessageDialog(this, "Added Failed");
            }
//        String sql = "INSERT INTO `book details`(`BookType`,`BookTitle`,`BookAuthor`,`BookId`,`BookCategory`) VALUES ('" + cmbbooktype.getSelectedItem().toString() + "','" + txtbooktitle.getText() + "','" + txtbookauthor.getText() + "','" + txtbookid.getText() + "','" + txtBookCat.getText() + "')";
//
//        try {
//            PreparedStatement ps = conn.prepareStatement(sql);
//            ps.executeUpdate();
//            ps.close();
//            JOptionPane.showMessageDialog(null, "Add user successfully");
//
//            cmbbooktype.getSelectedItem();
//            txtbooktitle.setText("");
//            txtbookauthor.setText("");
//            txtbookid.setText("");
//            txtBookCat.setText("");
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, "Error" + e.getMessage());
//            e.printStackTrace();
//        }
//    }
        } catch (SQLException ex) {
            Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnsaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFileEdit;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnsave;
    private javax.swing.JComboBox<String> cmbbooktype;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblBookCat;
    private javax.swing.JLabel lblbookauthor;
    private javax.swing.JLabel lblbookid;
    private javax.swing.JLabel lblbooktitle;
    private javax.swing.JLabel lblbooktype;
    private javax.swing.JTextField txtBookCat;
    private javax.swing.JTextField txtbookauthor;
    private javax.swing.JTextField txtbookid;
    private javax.swing.JTextField txtbooktitle;
    // End of variables declaration//GEN-END:variables
}
